### ISSUE TITLE
Result sets limited to 10,000 rows

### ISSUE THREAD

**Issue by marians** [crate/crash#101]
I tried using `crash` as a dump tool to export an entire table. The table has 77K entries, but obviously only 10K rows were exported. I got this message at the end:

```
SELECT 10000 rows in set (1.780 sec)
```

Is this limit imposed by crash, or is it something general in Crate?

**Comment by chaudum** [comment]
10K is an internal limit in Crate (if no `LIMIT` if specified in `SELECT` statement), not in crash.

However, don't use crash as a dump tool! The client does not stream data from the server, but loads the whole response into memory. Use `COPY TO` [docs](https://crate.io/docs/reference/sql/dml.html#import-export) instead. This will output `JSON` that can be imported easily into Crate again using `COPY FROM`.

**Comment by marians** [comment]
Thanks for the reply!

As for COPY TO: I have to run crate as a Docker process and I'd like to run the dump/backup task in a different Docker container. If possible, I'd like to avoid giving them a shared volume, which means the backup tool wouldn't have access to the written file.

I'll probably have to write my own streaming client which paginates through the table.
