### ISSUE TITLE
crash wastes multiple lines on the bottom of the shell window

### ISSUE THREAD

**Issue by reversefold** [crate/crash#117]
I've noticed with the upgrade from crate 0.51.6 to 0.54.4 that the supplied crash leaves multiple lines empty below the shell prompt to the bottom of the shell window. In one check at least I'm seeing 7 empty lines that I can't use and if I make the window shorter than 8 lines I get an error about the window being too small.

**Comment by joemoe** [comment]
hi, @reversefold we fixed this already and provide a release soon.

**Comment by celaus** [comment]
Hi, @reversefold - this is actually the space we use for our autocompletion to appear :smile: if this is a huge problem for you we can think about a better solution but until then we would like to keep our autocompletion window 7 lines long.

Cheers, Clasu

**Comment by joemoe** [comment]
sorry @reversefold this was the wrong issue.

**Comment by reversefold** [comment]
Hmm, I see. It's not a huge problem, but it was unexpected. I've never found the autocompletion that useful myself since it doesn't seem to be context sensitive and seems to suggest options which don't make sense.

**Comment by celaus** [comment]
@reversefold We have added a story to change that. We will let you know when it's finished :)

**Comment by reversefold** [comment]
Great. I'd also suggest trying to make those 7 lines available when autocomplete is not in use, but I understand that this is a harder thing to accomplish. Maybe the autocomplete could only come up when tab is pressed (like most autocompletes) or perhaps even an option to turn off the autocomplete completely to reclaim the space.

**Comment by chaudum** [comment]
@reversefold 
it is now possible to disable autocomplete to make the lines available
https://github.com/crate/crash/blob/master/CHANGES.txt#L17-L19
it will be released with the next major version of crash
