### ISSUE TITLE
How to cancel long lasting SELECTs?

### ISSUE THREAD

**Issue by githubmui** [crate/crash#121]
Hi,
it tried to quit a long lasting SELECT with Ctrl-C or Ctrl-Break. 
My current CRASH version 0.16.0 quit not only the SELECT but also itself.
Maybe this is a bug or is there eventually a shortcut to quit only the SELECT?
BTW: If the SELECT is finished then Ctrl-C doesn't break the shell.

**Comment by chaudum** [comment]
`Ctrl-C` should only interrupt the SELECT - however it does not KILL the query!
This has been implemented recently and is in `0.16.0` https://github.com/crate/crash/commit/b546babaf9a3b48f7f4df9834d18f40f23d17dee
`Ctlr-D` quits the crash

What operating system and Python version do you use?

**Comment by githubmui** [comment]
Hi, my Python version is 3.5.1 and tested it on windows.

**Comment by chaudum** [comment]
@githubmui thanks, we'll have a look!

**Comment by mikethebeer** [comment]
Hi @githubmui. I have tested it with your specs on a windows 8 and 10 machine and it works fine there (see screen). Did you try it the same as I did? So as @chaudum said `Ctrl-C` will only interrupt the shell input command. If you want to kill the job its necessary to run `KILL ALL` or `KILL <job_id>` (see https://crate.io/docs/reference/sql/reference/kill.html). Hope I could help.
![capture](https://cloud.githubusercontent.com/assets/6863216/14170183/7fa91980-f72c-11e5-9402-74a295ae08bb.PNG)

**Comment by githubmui** [comment]
I tested with a simple table with three columns (string, integer and timestamp) and no primary key. The table has got thousend of rows. 
Then I did a SELECT * from TABLE_NAME and the rows were scrolling over the screen.
While scrolling, I pressed CTRL-C and the SELECT statement were broken and also the crash shell itself.

**Comment by mikethebeer** [comment]
Hi @githubmui, 
thanks, I was able to reproduce it. We have already a fix for it in `master` branch. It will be also fixed in the next feature release.

**Comment by githubmui** [comment]
Thx!
