### ISSUE TITLE
upgrade docs build system

### ISSUE THREAD

**Issue by mechanomi** [crate/crash#329]
this repo uses the old Crate docs build system. we should update it to use the new build system (https://github.com/crate/docs)

for instructions, see here: https://github.com/crate/crate-howtos/issues/163

**Comment by infoverload** [comment]
I am interested in this

**Comment by mechanomi** [comment]
@infoverload please feel free. however, note: this is one of the projects I left until last because crash itself is a Python project. so the Python that exists to package and test crash itself needs disentangling from the Python (Sphinx, etc.) that builds the docs

so I would see this as a three-stage process:

- [ ] modify the existing build/setup infrastructure so that it is completely unaware of anything in the `docs/` directory
- [ ] gut any existing docs build infrastructure
- [ ] drop in the new docs build system

I am not sure whether crash actually uses the docs for testing. I know that crate/crate makes extensive use of *doctests* *within* the docs. this is one of the reasons I chose to leave crate/crate until last. because figuring out how to tease all that apart is going to be a challenge

**Comment by mechanomi** [comment]
fixed by https://github.com/crate/crash/pull/341
