### ISSUE TITLE
Update prompt-toolkit dependency to 3.0.x

### ISSUE THREAD

**Issue by mfussenegger** [crate/crash#338]
[prompt_toolkit](https://github.com/prompt-toolkit/python-prompt-toolkit) 3.0 has been out for a while.

I think we could update the dependency

**Comment by avats-dev** [comment]
I think I've to update this line https://github.com/crate/crash/blob/9177c001ce73eb80c295ccb9bc21ef23edbf72a7/setup.py#L33 , right @mfussenegger ? Should I open a PR with the changes?

**Comment by mfussenegger** [comment]
Yes you've to update that line. Maybe it's also necessary to make some other adjustements depending on the changes within prompt-toolkit. 


PR would be nice :+1:
