### ISSUE TITLE
Update branch protections to include new GitHub Actions docs.yml workflow

### ISSUE THREAD

**Issue by mechanomi** [crate/crash#345]
https://github.com/crate/crash/pull/341 added a GitHub Actions docs.yml workflow and removed the Travis CI tests configuration

accordingly, the branch protections for `master` need to be updated to:

- _no longer require_ the Travis CI checks
- _require_ the new GitHub Actions docs.yml workflow

in case it helps, the current [.mergify.yml](https://github.com/crate/crash/blob/master/.mergify.yml) configuration identifies the correct tests to include (lines starting with `status-success`)

**Comment by mechanomi** [comment]
can a @crate/sysadmins please review and take the necessary actions to close this issue? I do not have the permissions necessary to view or modify the current branch protections (it may be the case that the repository is already set up correctly, in which case a simple confirmation of that fact would be enough to close this issue imo)

**Comment by chaudum** [comment]
@mechanomi I updated the branch protection settings. You can verify them in PR https://github.com/crate/crash/pull/346

**Comment by mechanomi** [comment]
@chaudum thank you!

your PR correctly had all three docs tests failing and blocking the merge. I attempted to rebase to drop your commit to see if the tests would pass, but GitHub interpreted this as merge and closed the PR. (a merge of zero commits) unexpected behavior, but no harm done

I'll close this issue as fixed now!
