### ISSUE TITLE
Inconsistent spacing around printed runtime

### ISSUE THREAD

**Issue by hammerhead** [crate/crash#384]
For some types of statements, there are two spaces between the message (`1 row affected`) and the runtime (`0.172 sec`) instead of one.

```
cr> SELECT 1;
+---+
| 1 |
+---+
| 1 |
+---+
SELECT 1 row in set (0.002 sec)
                   ^ one space
cr> CREATE TABLE a (b INTEGER);
CREATE OK, 1 row affected  (0.172 sec)
                          ^ two spaces
```

**Comment by amotl** [comment]
Thank you for the report. The flaw has been fixed with GH-389, and the fix will be part of the next release.
