### ISSUE TITLE
Make it easier to discover available output formats

### ISSUE THREAD

**Issue by mfussenegger** [crate/crash#409]
The available formats are listed [in the docs](https://cratedb.com/docs/crate/crash/en/latest/run.html#command-line-options) but they're not easy to discover when using the CLI.

`crash --help` shows:

> --format FORMAT       the output FORMAT of the SQL response

`crash --format` shows:

> crash: error: argument --format: expected one argument

`crash --format invalid` finally shows them:

> crash: error: argument --format: invalid choice: 'invalid' (choose from 'tabular', 'json', 'csv', 'raw', 'mixed', 'dynamic', 'json_row')

Not sure how to best solve this. Maybe `--help` could include a hint, or `--format` without any other argument could list them

**Comment by amotl** [comment]
Hi Mathias,

thank you for your suggestion. An improvement to display the list of available output formats using `crash --help` has been implemented with GH-412. It has been included into crash 0.30.1, which is available from PyPI now.

With kind regards,
Andreas.
