### ISSUE TITLE
Documentation feedback on /docs/run.rst

### ISSUE THREAD

**Issue by msbt** [crate/crash#430]
### Documentation feedback

 
- Page title: Running Crash
- Page URL: https://cratedb.com/docs/crate/crash/en/latest/run.html
- Source: https://github.com/crate/crash/blob/master/docs/run.rst

---

Could we either use `loading="lazy"` or better/other compression (e.g. ezgif.com) for images? There's an 8MB gif which is quite big

**Comment by amotl** [comment]
Hi. Are you referring to the pager program animation?

https://cratedb.com/docs/crate/crash/en/latest/run.html#using-a-pager-program

I am so sorry. I just added the link without checking its resource size. We need to get rid of it again. Thanks!

**Comment by msbt** [comment]
Ah yes, that's the one, thanks for adding the anchor to clarify things! No need to get rid of it, if we could just add `loading="lazy"` as attribute, then it won't load until you scroll to that point.

**Comment by amotl** [comment]
Ah all right. Let's do it!

**Comment by msbt** [comment]
Just checked it out, it's embedded as a `figure`, couldn't find lazy loading options for that, what's the way to go here?

**Comment by amotl** [comment]
Is it possible to use another markup option, maybe from MyST?

**Comment by msbt** [comment]
@amotl could we just use the same syntax as in https://github.com/crate/crate-clients-tools/blob/main/docs/status.md?plain=1#L124 or does that work only with `.md` files?

**Comment by amotl** [comment]
I see that [run.rst](https://github.com/crate/crash/blob/master/docs/run.rst?plain=1) has tables and stuff, so converting is probably not a one-minute job. Let's try the [raw data pass-through](https://docutils.sourceforge.io/docs/ref/rst/directives.html#raw-data-pass-through) option.
